# Generated by Django 5.1.6 on 2025-02-12 14:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "car_model",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("engine_type", models.CharField(max_length=255)),
                ("horsepower", models.IntegerField()),
                ("weight", models.DecimalField(decimal_places=2, max_digits=6)),
                ("year_manufactured", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                ("driver_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField()),
                ("nationality", models.CharField(max_length=255)),
                ("points", models.IntegerField(default=0)),
                ("career_points", models.IntegerField(default=0)),
                ("championships_won", models.IntegerField(default=0)),
                ("total_race_wins", models.IntegerField(default=0)),
                (
                    "profile_image_url",
                    models.URLField(validators=[django.core.validators.URLValidator()]),
                ),
                ("driver_number", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("reserve", "Reserve"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                ("contract_id", models.AutoField(primary_key=True, serialize=False)),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apexData.driver",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Circuit",
            fields=[
                ("circuit_id", models.AutoField(primary_key=True, serialize=False)),
                ("circuit_name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("track_length", models.DecimalField(decimal_places=2, max_digits=5)),
                ("total_laps", models.IntegerField()),
                (
                    "circuit_map_url",
                    models.URLField(validators=[django.core.validators.URLValidator()]),
                ),
                ("number_of_drs_zones", models.IntegerField()),
                ("lap_record", models.DurationField()),
                ("first_grand_prix", models.IntegerField()),
                (
                    "lap_record_holder",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="apexData.driver",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DriverTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apexData.driver",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Race",
            fields=[
                ("race_id", models.AutoField(primary_key=True, serialize=False)),
                ("race_name", models.CharField(max_length=255)),
                ("date", models.DateField()),
                (
                    "race_status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=10,
                    ),
                ),
                ("weather_conditions", models.CharField(max_length=255)),
                ("safety_car_deployments", models.IntegerField(default=0)),
                ("red_flag_deployments", models.IntegerField(default=0)),
                ("sprint_race", models.BooleanField(default=False)),
                ("season", models.IntegerField()),
                ("round_number", models.IntegerField()),
                (
                    "circuit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apexData.circuit",
                    ),
                ),
            ],
            options={
                "unique_together": {("season", "round_number")},
            },
        ),
        migrations.CreateModel(
            name="PitStop",
            fields=[
                ("pit_stop_id", models.AutoField(primary_key=True, serialize=False)),
                ("lap_number", models.IntegerField()),
                ("pit_stop_time", models.DecimalField(decimal_places=2, max_digits=4)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apexData.driver",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apexData.race"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Penalty",
            fields=[
                ("penalty_id", models.AutoField(primary_key=True, serialize=False)),
                ("reason", models.CharField(max_length=255)),
                ("time_penalty", models.DecimalField(decimal_places=2, max_digits=4)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apexData.driver",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apexData.race"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("team_id", models.AutoField(primary_key=True, serialize=False)),
                ("team_name", models.CharField(max_length=255)),
                ("principal_name", models.CharField(max_length=255)),
                ("budget", models.DecimalField(decimal_places=2, max_digits=10)),
                ("constructor_points", models.IntegerField(default=0)),
                ("championships_won", models.IntegerField(default=0)),
                (
                    "logo_url",
                    models.URLField(validators=[django.core.validators.URLValidator()]),
                ),
                ("base_location", models.CharField(max_length=255)),
                ("first_season", models.IntegerField()),
                (
                    "drivers",
                    models.ManyToManyField(
                        through="apexData.DriverTeam", to="apexData.driver"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                ("sponsor_id", models.AutoField(primary_key=True, serialize=False)),
                ("sponsor_name", models.CharField(max_length=255)),
                (
                    "contribution_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apexData.team"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="driverteam",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="apexData.team"
            ),
        ),
        migrations.CreateModel(
            name="CarTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apexData.car"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apexData.team"
                    ),
                ),
            ],
            options={
                "unique_together": {("car", "team")},
            },
        ),
        migrations.AddField(
            model_name="car",
            name="teams",
            field=models.ManyToManyField(
                through="apexData.CarTeam", to="apexData.team"
            ),
        ),
        migrations.CreateModel(
            name="ChampionshipStandings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.IntegerField()),
                ("round_number", models.IntegerField()),
                ("points", models.IntegerField()),
                ("position", models.IntegerField()),
                ("wins", models.IntegerField(default=0)),
                ("podiums", models.IntegerField(default=0)),
                ("dnfs", models.IntegerField(default=0)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apexData.driver",
                    ),
                ),
            ],
            options={
                "unique_together": {("season", "round_number", "driver")},
            },
        ),
        migrations.CreateModel(
            name="QualifyingResult",
            fields=[
                ("qualifying_id", models.AutoField(primary_key=True, serialize=False)),
                ("q1_time", models.DurationField(blank=True, null=True)),
                ("q2_time", models.DurationField(blank=True, null=True)),
                ("q3_time", models.DurationField(blank=True, null=True)),
                ("final_position", models.IntegerField()),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apexData.driver",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apexData.race"
                    ),
                ),
            ],
            options={
                "unique_together": {("race", "driver")},
            },
        ),
        migrations.CreateModel(
            name="RaceResult",
            fields=[
                ("result_id", models.AutoField(primary_key=True, serialize=False)),
                ("position", models.IntegerField()),
                ("laps_completed", models.IntegerField()),
                ("fastest_time", models.DurationField()),
                ("grid_position", models.IntegerField()),
                ("points_earned", models.IntegerField()),
                ("dnf_status", models.BooleanField(default=False)),
                ("dnf_reason", models.CharField(blank=True, max_length=255, null=True)),
                ("gap_to_leader", models.DurationField(blank=True, null=True)),
                ("number_of_pit_stops", models.IntegerField(default=0)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apexData.driver",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apexData.race"
                    ),
                ),
            ],
            options={
                "unique_together": {("race", "position")},
            },
        ),
        migrations.CreateModel(
            name="SprintResult",
            fields=[
                ("sprint_id", models.AutoField(primary_key=True, serialize=False)),
                ("position", models.IntegerField()),
                ("points_earned", models.IntegerField()),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apexData.driver",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apexData.race"
                    ),
                ),
            ],
            options={
                "unique_together": {("race", "driver")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="driverteam",
            unique_together={("driver", "team")},
        ),
        migrations.CreateModel(
            name="ConstructorStandings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.IntegerField()),
                ("round_number", models.IntegerField()),
                ("points", models.IntegerField()),
                ("position", models.IntegerField()),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apexData.team"
                    ),
                ),
            ],
            options={
                "unique_together": {("season", "round_number", "team")},
            },
        ),
    ]
