# Generated by Django 5.1.6 on 2025-02-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apexData", "0002_alter_driver_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="podiums",
            field=models.IntegerField(default=0),
        ),
    ]
