# Generated by Django 5.1.6 on 2025-02-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apexData", "0003_driver_podiums"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={"ordering": ["-points"]},
        ),
        migrations.AddField(
            model_name="driver",
            name="dnfs",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="driver",
            name="wins",
            field=models.IntegerField(default=0),
        ),
    ]
